require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  # rake will show a novel's worth of circular require warnings w/o this
  t.warning = false
  t.test_files = FileList["Array#reverse.rb"]
end

task :default => :test
